---
apiVersion: 'apps/v1'
kind:       'Deployment'
metadata:
  name: {{ include "civiform.fullname" . }}
  labels:
    {{- include "civiform.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "civiform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "civiform.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name:   'application-conf'
          configMap:
            name: 'application-conf'
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name:      'application-conf'
              mountPath: '/civiform-server-0.0.1/conf'

          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
...
