name: Inputs Test

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

      probers_enabled:
        description: 'Runs probers when checked'
        default: true
        required: true
        type: boolean


jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Display github.event.inputs.probers_enabled
        run: "echo ${{ github.event.inputs.probers_enabled }}"

      - name: Display github.event.inputs.environment
        run: "echo ${{ github.event.inputs.environment }}"

      - name: Display vars.DEPLOY_SUBDOMAIN
        run: "echo ${{ vars.DEPLOY_SUBDOMAIN }}"

      - name: Display vars.DEPLOY_TARGET
        run: "echo ${{ vars.DEPLOY_TARGET }}"
