name: Inputs Test

on:
  workflow_dispatch:
    inputs:
      site-env:
        type: choice
        description: Site location
        options: 
        - test
        - staging

      environment:
        type: environment

        
      probers_enabled:
        description: 'Runs probers when checked'
        default: true
        required: true
        type: boolean


jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Display value
        run: "echo ${{ github.event.inputs.probers_enabled }}"
