name: Inputs Test

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        default: staging
        required: true
        
      probers_enabled:
        type: boolean
        description: 'Runs probers when checked'
        default: true
        required: true
        
  schedule:
    - cron: '*/5 * * * *'
        
jobs:
  test-job:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'staging' }}
    steps:
      - name: Display 
        run: |
          echo "github.event.inputs.probers_enabled: ${{ github.event.inputs.probers_enabled }}"
          echo "github.event.inputs.environment: ${{ github.event.inputs.environment }}"
          echo "vars.SUBDOMAIN: ${{ vars.SUBDOMAIN }}"
