name: Inputs Test

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

      probers_enabled:
        description: 'Runs probers when checked'
        default: true
        required: true
        type: boolean


jobs:
  test-job:
    runs-on: ubuntu-latest
    environment: ${{ vars.ENVIRONMENT_STAGE }}
    
    steps:
      - name: Display 
        run: |
          echo "${{ vars.ENVIRONMENT_STAGE }}"
          echo "${{ github.event.inputs.probers_enabled }}"
          echo "${{ github.event.inputs.environment }}"
          echo "${{ vars.DEPLOY_SUBDOMAIN }}"
          echo "${{ vars.DEPLOY_TARGET }}"
