name: Run Probers Only

on:
  workflow_dispatch: {}
  workflow_call:

#permissions: read-all

# Two probers running at once can break each other.
concurrency:
  group: stagingenvironment
  cancel-in-progress: true

jobs:
  run_prober:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Run Prober Tests 
        env:
          BASE_URL: "https://civiformtest.seattle.gov"
          TEST_USER_LOGIN: ${{ secrets.TEST_USER_LOGIN }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 70
          max_attempts: 1
          retry_wait_seconds: 15
          command: bin/run-prober
