name: Test GIS

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 * * * *'

permissions: {}

jobs:
  test-gis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run gis testing script
        run: bin/test_gis.sh
              
      - name: Send message to ms teams
        uses: dhollerbach/actions.send-message-to-ms-teams@1.0.10
        with:
          webhook: '${{ secrets.MICROSOFT_TEAMS_WEBHOOK_URI }}'
          message: 'test message!'
