name: Test GIS

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 * * * *'

permissions: {}

jobs:
  test-gis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run gis testing script
        run: bin/test_gis.sh
