name: Test API
run-name: Test API

on:
  workflow_dispatch: 
    inputs:
      environment:
        type: environment
        default: test
        required: true

permissions: {}

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: |
          cd qa
          npm install

      - name: Run
        env:
          BASE_URL: 'https://${{ vars.SUBDOMAIN }}.seattle.gov'
          API_TOKEN: ${{ secrets.API_TOKEN }}
          PROGRAM_SLUGS: ${{ secrets.PROGRAM_SLUGS }}
        run: cd qa && npx playwright test
